[package]
name = "brainrotfps/brainrotfps"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
# Add your dependencies here, for example:
# Promise = "evaera/promise@4.0.0"
# Signal = "stravant/goodsignal@0.2.0"
# Knit = "sleitnick/knit@1.7.0"
zoneplus = "essentiallyblue/zoneplus@3.2.2"
profilestore = "vyon/profilestore@1.0.3"
bytenet = "ffrostflame/bytenet@0.4.6"
signal = "sleitnick/signal@2.0.3"
cmdr = "evaera/cmdr@1.12.0"
janitor = "howmanysmall/janitor@1.18.3"
promise = "evaera/promise@4.0.0"
testez = "roblox/testez@0.4.1"
spring = "jaeymo/spring@1.0.1"
[server-dependencies]
# Server-only packages go here

[dev-dependencies]
# Development dependencies go here
# TestEZ = "roblox/testez@0.4.1"
